import { ActivityEvent, UserProfile, ChatThread, CommunityPost, CategoryType } from './types';

export const PUNE_AREAS = [
  'All Pune',
  'Tatwade',
  'Wakad',
  'Baner',
  'Hinjewadi',
  'Balewadi',
  'Kothrud',
  'Koregaon Park',
  'Viman Nagar',
  'FC Road',
];

export const CATEGORY_ICONS: Record<CategoryType, { icon: string; bg: string; text: string }> = {
  Coffee: { icon: '☕', bg: 'bg-amber-100 dark:bg-amber-950/40', text: 'text-amber-800 dark:text-amber-300' },
  Gaming: { icon: '🎮', bg: 'bg-purple-100 dark:bg-purple-950/40', text: 'text-purple-800 dark:text-purple-300' },
  Sports: { icon: '🏸', bg: 'bg-emerald-100 dark:bg-emerald-950/40', text: 'text-emerald-800 dark:text-emerald-300' },
  Food: { icon: '🍕', bg: 'bg-orange-100 dark:bg-orange-950/40', text: 'text-orange-800 dark:text-orange-300' },
  Movies: { icon: '🎬', bg: 'bg-rose-100 dark:bg-rose-950/40', text: 'text-rose-800 dark:text-rose-300' },
  Travel: { icon: '✈️', bg: 'bg-blue-100 dark:bg-blue-950/40', text: 'text-blue-800 dark:text-blue-300' },
  Trekking: { icon: '🥾', bg: 'bg-lime-100 dark:bg-lime-950/40', text: 'text-lime-800 dark:text-lime-300' },
  Art: { icon: '🎨', bg: 'bg-pink-100 dark:bg-pink-950/40', text: 'text-pink-800 dark:text-pink-300' },
  Music: { icon: '🎵', bg: 'bg-indigo-100 dark:bg-indigo-950/40', text: 'text-indigo-800 dark:text-indigo-300' },
  Technology: { icon: '💻', bg: 'bg-cyan-100 dark:bg-cyan-950/40', text: 'text-cyan-800 dark:text-cyan-300' },
};

export const INITIAL_USER: UserProfile = {
  id: 'user-me',
  name: 'Pratik Sharma',
  role: 'user',
  age: 24,
  city: 'Pune',
  area: 'Wakad',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  bio: 'Product designer living in Wakad. Love coffee meetups, casual badminton matches, weekend treks, and exploring food spots around Pune.',
  interests: ['Coffee', 'Gaming', 'Trekking', 'Sports', 'Food'],
  isVerified: true,
  eventsJoinedCount: 14,
  eventsHostedCount: 3,
  connectionsCount: 38,
};

export const MOCK_PEOPLE: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Aarav Mehta',
    role: 'user',
    age: 23,
    city: 'Pune',
    area: 'Wakad',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    bio: 'Techie by day, gamer & specialty coffee enthusiast by night.',
    interests: ['Coffee', 'Gaming', 'Travel'],
    commonInterests: 3,
    isVerified: true,
    eventsJoinedCount: 9,
    eventsHostedCount: 2,
    connectionsCount: 24,
  },
  {
    id: 'user-2',
    name: 'Ananya Deshmukh',
    role: 'user',
    age: 25,
    city: 'Pune',
    area: 'Baner',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400',
    bio: 'Always up for a morning trek at Vetal Tekdi or trying new ramen spots in Baner.',
    interests: ['Trekking', 'Food', 'Art'],
    commonInterests: 2,
    isVerified: true,
    eventsJoinedCount: 18,
    eventsHostedCount: 5,
    connectionsCount: 45,
  },
  {
    id: 'user-3',
    name: 'Rohan Joshi',
    role: 'user',
    age: 26,
    city: 'Pune',
    area: 'Hinjewadi',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    bio: 'Looking for doubles partners for badminton & board game weekend marathons.',
    interests: ['Sports', 'Gaming', 'Movies'],
    commonInterests: 2,
    isVerified: false,
    eventsJoinedCount: 6,
    eventsHostedCount: 1,
    connectionsCount: 19,
  },
  {
    id: 'user-4',
    name: 'Priya Kulkarni',
    role: 'user',
    age: 22,
    city: 'Pune',
    area: 'Tatwade',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    bio: 'Photography student in Pune. Excited to meet fellow creators & foodies!',
    interests: ['Coffee', 'Art', 'Food'],
    commonInterests: 2,
    isVerified: true,
    eventsJoinedCount: 12,
    eventsHostedCount: 4,
    connectionsCount: 31,
  },
  {
    id: 'user-5',
    name: 'Vikram Singh',
    role: 'user',
    age: 27,
    city: 'Pune',
    area: 'Koregaon Park',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    bio: 'Avid traveler & trekker. Planning Sinhagad sunrise trips and cafe hops.',
    interests: ['Trekking', 'Travel', 'Coffee'],
    commonInterests: 3,
    isVerified: true,
    eventsJoinedCount: 22,
    eventsHostedCount: 8,
    connectionsCount: 62,
  },
];

export const MOCK_EVENTS: ActivityEvent[] = [
  {
    id: 'event-1',
    title: 'Coffee & Conversations ☕',
    category: 'Coffee',
    icon: '☕',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800',
    location: 'Café Peter, Wakad, Pune',
    area: 'Wakad',
    distanceKm: 0.8,
    date: 'Saturday, 15 Aug',
    time: '5:00 PM',
    isToday: false,
    isThisWeekend: true,
    joinedCount: 8,
    totalSpots: 10,
    price: 0,
    description: 'Meet new people over artisan coffee, relaxed conversation, and light social icebreaker games. Great for newcomers in Pune or anyone wanting to break out of routine!',
    host: {
      name: 'MILO Community Host (Ananya)',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400',
      role: 'Verified Community Ambassador',
    },
    safetyNote: 'Public venue • Reserved cozy table • Community guidelines apply',
    participants: [
      { id: 'user-me', name: 'Pratik', avatar: INITIAL_USER.avatar },
      { id: 'user-1', name: 'Aarav', avatar: MOCK_PEOPLE[0].avatar },
      { id: 'user-2', name: 'Ananya', avatar: MOCK_PEOPLE[1].avatar, isHost: true },
      { id: 'user-4', name: 'Priya', avatar: MOCK_PEOPLE[3].avatar },
      { id: 'user-6', name: 'Siddharth', avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-7', name: 'Neha', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-8', name: 'Kabir', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-9', name: 'Tanvi', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400' },
    ],
    vibes: ['Casual', 'Friendly', 'No Pressures', 'Public Cafe'],
  },
  {
    id: 'event-2',
    title: 'Weekend Badminton Smash 🏸',
    category: 'Sports',
    icon: '🏸',
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=800',
    location: 'Solar Sports Arena, Hinjewadi Ph 1',
    area: 'Hinjewadi',
    distanceKm: 1.5,
    date: 'Saturday, 15 Aug',
    time: '8:00 AM',
    isToday: false,
    isThisWeekend: true,
    joinedCount: 5,
    totalSpots: 6,
    price: 150,
    description: '2 hours of doubles badminton courts reserved! Beginners and intermediate players welcome. Extra rackets available if needed.',
    host: {
      name: 'Rohan Joshi',
      avatar: MOCK_PEOPLE[2].avatar,
      role: 'Sports Enthusiast',
    },
    safetyNote: 'Indoor Synthetic Court • Non-marking shoes mandatory',
    participants: [
      { id: 'user-3', name: 'Rohan', avatar: MOCK_PEOPLE[2].avatar, isHost: true },
      { id: 'user-1', name: 'Aarav', avatar: MOCK_PEOPLE[0].avatar },
      { id: 'user-10', name: 'Varun', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-11', name: 'Isha', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-12', name: 'Aditya', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400' },
    ],
    vibes: ['Active', 'Sports', 'Energy', 'Friendly Match'],
  },
  {
    id: 'event-3',
    title: 'PC Gaming & Board Games Night 🎮',
    category: 'Gaming',
    icon: '🎮',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800',
    location: 'Nexus Gaming Lounge, High Street, Baner',
    area: 'Baner',
    distanceKm: 2.4,
    date: 'Friday, 14 Aug',
    time: '7:00 PM',
    isToday: true,
    isThisWeekend: false,
    joinedCount: 7,
    totalSpots: 8,
    price: 200,
    description: 'Valorant custom lobbies, FIFA tournaments, Catan, and Secret Hitler board games. Snacks & drinks available on location.',
    host: {
      name: 'Aarav Mehta',
      avatar: MOCK_PEOPLE[0].avatar,
      role: 'Guild Leader',
    },
    safetyNote: 'Public Commercial Gaming Lounge • Verified Host',
    participants: [
      { id: 'user-1', name: 'Aarav', avatar: MOCK_PEOPLE[0].avatar, isHost: true },
      { id: 'user-me', name: 'Pratik', avatar: INITIAL_USER.avatar },
      { id: 'user-3', name: 'Rohan', avatar: MOCK_PEOPLE[2].avatar },
      { id: 'user-13', name: 'Dev', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-14', name: 'Meera', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-15', name: 'Karan', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-16', name: 'Shruti', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400' },
    ],
    vibes: ['Chill', 'Fun', 'Gamer Friendly', 'Night Out'],
  },
  {
    id: 'event-4',
    title: 'Puneri Street Food & Irani Chai Crawl 🍕',
    category: 'Food',
    icon: '🍕',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=800',
    location: 'Goodluck Cafe & FC Road Food Walk',
    area: 'FC Road',
    distanceKm: 4.2,
    date: 'Sunday, 16 Aug',
    time: '6:00 PM',
    isToday: false,
    isThisWeekend: true,
    joinedCount: 9,
    totalSpots: 12,
    price: 100,
    description: 'Starting with Bun Maska & Chai at Goodluck, followed by Vaishali Dosa, SP’s Biryani bites, and Mastani thick shakes on FC road.',
    host: {
      name: 'Priya Kulkarni',
      avatar: MOCK_PEOPLE[3].avatar,
      role: 'Food Explorer',
    },
    safetyNote: 'Open Group Walk • Bustling Public Street',
    participants: [
      { id: 'user-4', name: 'Priya', avatar: MOCK_PEOPLE[3].avatar, isHost: true },
      { id: 'user-2', name: 'Ananya', avatar: MOCK_PEOPLE[1].avatar },
      { id: 'user-5', name: 'Vikram', avatar: MOCK_PEOPLE[4].avatar },
      { id: 'user-17', name: 'Rahul', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400' },
      { id: 'user-18', name: 'Simran', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400' },
    ],
    vibes: ['Foodies', 'Street Food', 'Walking Tour', 'Good Vibes'],
  },
  {
    id: 'event-5',
    title: 'Vetal Tekdi Sunrise Trek & Breakfast 🥾',
    category: 'Trekking',
    icon: '🥾',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    location: 'Base Gate, Kothrud / ARAI Tekdi, Pune',
    area: 'Kothrud',
    distanceKm: 3.8,
    date: 'Sunday, 16 Aug',
    time: '5:45 AM',
    isToday: false,
    isThisWeekend: true,
    joinedCount: 14,
    totalSpots: 15,
    price: 0,
    description: 'Brisk morning trail hike to Pune’s highest hill point for sunrise views over the city skyline, followed by South Indian breakfast nearby.',
    host: {
      name: 'Vikram Singh',
      avatar: MOCK_PEOPLE[4].avatar,
      role: 'Experienced Trek Leader',
    },
    safetyNote: 'Easy 3km Trail • Bring water bottle & comfortable shoes',
    participants: [
      { id: 'user-5', name: 'Vikram', avatar: MOCK_PEOPLE[4].avatar, isHost: true },
      { id: 'user-me', name: 'Pratik', avatar: INITIAL_USER.avatar },
      { id: 'user-2', name: 'Ananya', avatar: MOCK_PEOPLE[1].avatar },
      { id: 'user-1', name: 'Aarav', avatar: MOCK_PEOPLE[0].avatar },
    ],
    vibes: ['Nature', 'Sunrise', 'Fitness', 'Fresh Air'],
  },
  {
    id: 'event-6',
    title: 'Sci-Fi Movie & Popcorn Hangout 🎬',
    category: 'Movies',
    icon: '🎬',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800',
    location: 'PVR IMAX, The Pavilion Mall, SB Road',
    area: 'Baner',
    distanceKm: 3.1,
    date: 'Saturday, 15 Aug',
    time: '4:15 PM',
    isToday: false,
    isThisWeekend: true,
    joinedCount: 5,
    totalSpots: 10,
    price: 250,
    description: 'Catching the latest Sci-Fi blockbuster in IMAX, followed by coffee and film discussion at the mall courtyard.',
    host: {
      name: 'Rohan Joshi',
      avatar: MOCK_PEOPLE[2].avatar,
      role: 'Cinephile Host',
    },
    safetyNote: 'Public Multiplex • Group Ticket Booking Available',
    participants: [
      { id: 'user-3', name: 'Rohan', avatar: MOCK_PEOPLE[2].avatar, isHost: true },
      { id: 'user-4', name: 'Priya', avatar: MOCK_PEOPLE[3].avatar },
    ],
    vibes: ['Movies', 'IMAX', 'Discussion', 'Chill'],
  },
  {
    id: 'event-7',
    title: 'Weekend Escape to Mahabaleshwar ✈️',
    category: 'Travel',
    icon: '✈️',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    location: 'Pickup: Bhumkar Chowk, Tatwade',
    area: 'Tatwade',
    distanceKm: 1.2,
    date: 'Saturday, 22 Aug',
    time: '6:00 AM',
    isToday: false,
    isThisWeekend: false,
    joinedCount: 6,
    totalSpots: 8,
    price: 1200,
    description: 'Road trip in a shared comfortable SUV to foggy viewpoints, strawberry farms, and lake boating in Mahabaleshwar.',
    host: {
      name: 'Vikram Singh',
      avatar: MOCK_PEOPLE[4].avatar,
      role: 'Roadtripper',
    },
    safetyNote: 'Verified SUV Driver • Split fuel & stay cost transparently',
    participants: [
      { id: 'user-5', name: 'Vikram', avatar: MOCK_PEOPLE[4].avatar, isHost: true },
      { id: 'user-1', name: 'Aarav', avatar: MOCK_PEOPLE[0].avatar },
      { id: 'user-2', name: 'Ananya', avatar: MOCK_PEOPLE[1].avatar },
    ],
    vibes: ['Road Trip', 'Mountains', 'Nature', 'Weekend Getaway'],
  },
  {
    id: 'event-8',
    title: 'Acrylic Canvas & Pottery Workshop 🎨',
    category: 'Art',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800',
    location: 'High Street Art Studio, Balewadi',
    area: 'Balewadi',
    distanceKm: 2.8,
    date: 'Sunday, 16 Aug',
    time: '3:00 PM',
    isToday: false,
    isThisWeekend: true,
    joinedCount: 4,
    totalSpots: 8,
    price: 350,
    description: 'No prior experience needed! Materials, paints, and canvases provided. Guided by a local artist while listening to acoustic music.',
    host: {
      name: 'Priya Kulkarni',
      avatar: MOCK_PEOPLE[3].avatar,
      role: 'Art Host',
    },
    safetyNote: 'Cozy Studio • Paint aprons & supplies provided',
    participants: [
      { id: 'user-4', name: 'Priya', avatar: MOCK_PEOPLE[3].avatar, isHost: true },
      { id: 'user-me', name: 'Pratik', avatar: INITIAL_USER.avatar },
    ],
    vibes: ['Creative', 'Relaxing', 'Artistic', 'Aesthetic'],
  }
];

export const MOCK_CHAT_THREADS: ChatThread[] = [
  {
    id: 'thread-1',
    type: 'group',
    title: 'Coffee & Conversations ☕',
    avatar: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=200',
    lastMessage: 'Ananya: Super excited! Reserved the sofa corner near the terrace window for 5 PM.',
    timestamp: '10:42 AM',
    unreadCount: 2,
    participantsCount: 8,
    messages: [
      {
        id: 'msg-1',
        senderId: 'user-2',
        senderName: 'Ananya',
        senderAvatar: MOCK_PEOPLE[1].avatar,
        text: 'Hey everyone! 👋 Welcome to Saturday’s coffee meetup chat.',
        timestamp: '9:15 AM',
      },
      {
        id: 'msg-2',
        senderId: 'user-1',
        senderName: 'Aarav',
        senderAvatar: MOCK_PEOPLE[0].avatar,
        text: 'Hey Ananya! What time are we reaching Café Peter?',
        timestamp: '9:30 AM',
      },
      {
        id: 'msg-3',
        senderId: 'user-me',
        senderName: 'Pratik',
        senderAvatar: INITIAL_USER.avatar,
        text: 'I live nearby in Wakad so I will be there right around 4:55 PM ☕',
        timestamp: '10:15 AM',
        isSelf: true,
      },
      {
        id: 'msg-4',
        senderId: 'user-2',
        senderName: 'Ananya',
        senderAvatar: MOCK_PEOPLE[1].avatar,
        text: 'Super excited! Reserved the sofa corner near the terrace window for 5 PM.',
        timestamp: '10:42 AM',
      },
    ],
  },
  {
    id: 'thread-2',
    type: 'group',
    title: 'Weekend Badminton Smash 🏸',
    avatar: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=200',
    lastMessage: 'Rohan: Shuttlecocks are sorted! Don’t forget non-marking shoes guys.',
    timestamp: 'Yesterday',
    unreadCount: 0,
    participantsCount: 5,
    messages: [
      {
        id: 'msg-10',
        senderId: 'user-3',
        senderName: 'Rohan',
        senderAvatar: MOCK_PEOPLE[2].avatar,
        text: 'Shuttlecocks are sorted! Don’t forget non-marking shoes guys.',
        timestamp: 'Yesterday',
      },
    ],
  },
  {
    id: 'thread-3',
    type: 'direct',
    title: 'Aarav Mehta',
    avatar: MOCK_PEOPLE[0].avatar,
    lastMessage: 'Are you joining the Valorant gaming night this Friday?',
    timestamp: '2 hours ago',
    unreadCount: 1,
    messages: [
      {
        id: 'msg-20',
        senderId: 'user-1',
        senderName: 'Aarav',
        senderAvatar: MOCK_PEOPLE[0].avatar,
        text: 'Hey Pratik! Saw you are into gaming as well.',
        timestamp: '11:00 AM',
      },
      {
        id: 'msg-21',
        senderId: 'user-1',
        senderName: 'Aarav',
        senderAvatar: MOCK_PEOPLE[0].avatar,
        text: 'Are you joining the Valorant gaming night this Friday?',
        timestamp: '11:02 AM',
      },
    ],
  },
  {
    id: 'thread-4',
    type: 'direct',
    title: 'Priya Kulkarni',
    avatar: MOCK_PEOPLE[3].avatar,
    lastMessage: 'Thanks for saving a spot for the art workshop!',
    timestamp: '3 days ago',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-30',
        senderId: 'user-4',
        senderName: 'Priya',
        senderAvatar: MOCK_PEOPLE[3].avatar,
        text: 'Thanks for saving a spot for the art workshop!',
        timestamp: '3 days ago',
      },
    ],
  },
];

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    author: {
      name: 'Ananya Deshmukh',
      avatar: MOCK_PEOPLE[1].avatar,
      area: 'Baner',
      isVerified: true,
    },
    timeAgo: '2 hours ago',
    content: 'Had an unbelievable sunrise trek at Vetal Tekdi this morning with 12 MILO members! Started as complete strangers at 5:45 AM and ended up having South Indian filter coffee together at 8 AM. This is why I love MILO! 🌄☕',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    likes: 42,
    commentsCount: 9,
    sharesCount: 3,
    isLiked: true,
    category: 'Trekking',
  },
  {
    id: 'post-2',
    author: {
      name: 'Vikram Singh',
      avatar: MOCK_PEOPLE[4].avatar,
      area: 'Koregaon Park',
      isVerified: true,
    },
    timeAgo: '5 hours ago',
    content: 'Quick question for the Pune crew: What should we organize for this coming Sunday afternoon? 1) Acoustic Jam session in KP 2) Specialty Coffee & Board Games in Wakad 3) Bouldering/Climbing attempt in Hinjewadi? Drop your vote below! 👇',
    likes: 28,
    commentsCount: 15,
    sharesCount: 2,
    isLiked: false,
    category: 'Coffee',
  },
  {
    id: 'post-3',
    author: {
      name: 'Aarav Mehta',
      avatar: MOCK_PEOPLE[0].avatar,
      area: 'Wakad',
      isVerified: true,
    },
    timeAgo: '1 day ago',
    content: 'Just moved to Pune from Bangalore last week. Joined my first MILO badminton match yesterday and met 4 awesome friends straight away. If you are sitting on the fence about joining a meetup, just do it!',
    likes: 64,
    commentsCount: 12,
    sharesCount: 5,
    isLiked: true,
    category: 'Sports',
  },
];

export const TESTIMONIALS = [
  {
    quote: "I moved to Pune for work and knew nobody. I showed up alone for a coffee meetup in Wakad and ended up talking to six amazing people. I actually joined the weekend trek too!",
    name: "Aarav",
    age: 23,
    city: "Wakad, Pune",
    avatar: MOCK_PEOPLE[0].avatar,
  },
  {
    quote: "Unlike awkward apps where people cancel last minute, MILO is all about real plans in public places. The badminton group has become my weekly ritual!",
    name: "Rohan",
    age: 26,
    city: "Hinjewadi, Pune",
    avatar: MOCK_PEOPLE[2].avatar,
  },
  {
    quote: "As a woman living alone in Baner, safety was my #1 priority. MILO's public venues and verified host badges made me feel completely safe and welcomed.",
    name: "Ananya",
    age: 25,
    city: "Baner, Pune",
    avatar: MOCK_PEOPLE[1].avatar,
  },
  {
    quote: "My friends are always busy or glued to screens. With MILO, whenever I want to grab coffee, play board games, or hike, there's always a group going!",
    name: "Priya",
    age: 22,
    city: "Tatwade, Pune",
    avatar: MOCK_PEOPLE[3].avatar,
  },
];
